Entry.create!(name: 'Matz')
Entry.create!(name: 'Kats')
Entry.create!(name: 'DHH')
Entry.create!(name: 'Valim')
Entry.create!(name: 'Nic')
Entry.create!(name: 'Nunemaker')
Entry.create!(name: 'Patterson')
